<?php

namespace AppBundle\Repository;
use AppBundle\Entity\RaceSection;

/**
 * RaceSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
