<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Race;

/**
 * RaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForEvent($id)
    {
        return $this->findBy(array('event' => $id));
    }

    public function getOfficialName(Race $race) {
        $name = '';

        switch($race->getAgeClass()) {
            case 'Kind':
                if ($race->getGender() == 'w') {
                    $name = 'Mädchen';
                } elseif($race->getGender() == 'm') {
                    $name = 'Jungen';
                } else {
                    $name = 'JuM';
                }
                $name .= ' (';
                if ($race->getAgeMin() == $race->getAgeMax()) {
                    $name .= $race->getAgeMin();
                } else {
                    $name .= $race->getAgeMin().' bis '.$race->getAgeMax();
                }
                $name .= ' Jahre)';
                break;
            case 'Junior':
                if ($race->getGender() == 'w') {
                    $name = 'Juniorinnen';
                } else {
                    $name = 'Junioren';
                }

                if ($race->getAgeMin() == 15 && ($race->getAgeMax() == 16 || $race->getAgeMax() == $race->getAgeMin())) {
                    $name .= ' B';
                } elseif ($race->getAgeMin() == 17 && ($race->getAgeMax() == 18 || $race->getAgeMax() == $race->getAgeMin())) {
                    $name .= ' A';
                }
            break;
            case 'Senior':
                if ($race->getGender() == 'w') {
                    $name = 'Frauen';
                } elseif($race->getGender() == 'm') {
                    $name = 'Männer';
                } else {
                    $name = 'Senioren';
                }

                if ($race->getAgeMax() < 23) {
                    $name .= ' B';
                } elseif ($race->getAgeMin() > 22 && $race->getAgeMax() < 27) {
                    $name .= ' A';
                } else {
                    $name .= ' ('.$race->getAgeMin().' bis '.$race->getAgeMax().' Jahre)';
                }
            break;
            case 'Master':
                if ($race->getGender() == 'w') {
                    $name = 'Frauen (Masters)';
                } elseif($race->getGender() == 'm') {
                    $name = 'Männer (Masters)';
                } else {
                    $name = 'Masters';
                }
                $name .= ' ('.$race->getAgeMin().' bis '.$race->getAgeMax().' Jahre)';
            break;
            case 'Offen':
                $name = 'Offen';
                $name .= ' ('.$race->getAgeMin().' bis '.$race->getAgeMax().' Jahre)';
            break;
        }

        return $name;
    }

    private function getAgeClassSuffix($min, $max) {
        return "(".$min." - ".$max.")";
    }

}
