<?php

namespace AppBundle\Repository;

/**
 * RacingGroupMembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RacingGroupMembershipRepository extends \Doctrine\ORM\EntityRepository
{
}
