<?php

namespace AppBundle\Repository;
use AppBundle\Entity\RaceSection;

/**
 * RacingGroupsPerSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RacingGroupsPerSectionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextLaneForSection(RaceSection $raceSection)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('MAX(r.lane) maxNum')
            ->from('AppBundle:RacingGroupsPerSection', 'r')
            ->where($qb->expr()->eq('r.section', '?1'))
            ->setParameter(1, $raceSection->getId());
        return ((int) $qb->getQuery()->getSingleScalarResult()) + 1;
    }
}
