<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Race;
use AppBundle\Entity\RaceSection;
use AppBundle\Entity\Registration;

use Doctrine\ORM\EntityManager;

/**
 * Registration
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextLaneForSection(RaceSection $raceSection)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('MAX(r.lane) maxNum')
            ->from('AppBundle:Registration', 'r')
            ->where($qb->expr()->eq('r.section', '?1'))
            ->setParameter(1, $raceSection->getId());
        return ((int) $qb->getQuery()->getSingleScalarResult()) + 1;
    }

    public function changeRace(Registration $registration, Race $fromRace, Race $toRace)
    {
        if (is_null($registration)) {
            throw new \InvalidArgumentException('Registration must not be NULL');
        } elseif (is_null($fromRace)) {
            throw new \InvalidArgumentException('Source race must not be NULL');
        } elseif (is_null($toRace)) {
            throw new \InvalidArgumentException('Target race must not be NULL');
        }

        /** @var EntityManager $em */
        $em = $this->getEntityManager();
        /** @var \AppBundle\Repository\RaceRepository $raceRepo */
        $raceRepo = $em->getRepository('AppBundle:Race');

        /** @var RaceSection $section */
        $section = $raceRepo->getNextAvailableSection($toRace);

        // mark current team registration as changed and save the new race id
        $registration->setChangedTo($toRace);
        // create new registration for this team in target race
        $newReg = new Registration();
        $newReg->setSection($section)
            ->setLane($this->getNextLaneForSection($section))
            // the competitor team stays the same
            ->setTeam($registration->getTeam())
            ->setChangedFrom($fromRace);

        $em->persist($registration);
        $em->persist($newReg);
        $em->flush();
    }
}
