<?php

namespace AppBundle\Repository;

/**
 * TeamPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
