# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    app.token_controller:
        class: AppBundle\Controller\TokenController
        calls:
            - [setContainer, ["@service_container"]]
    app.timing_controller:
        class: AppBundle\Controller\TimingController
        calls:
            - [setContainer, ["@service_container"]]